version: "3"
services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.2/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - pgsql
      - redis
      - meilisearch
      - mailpit
  pgsql:
    image: "postgres:14.3"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "2csv"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - "sail-pgsql:/var/lib/postgresql/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "2csv", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
  pgsql_test:
    image: "postgres:14.3"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "2csv"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - "sail-pgsql_test:/var/lib/postgresql/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "2csv", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sail-redis:/data"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - "sail-meilisearch:/meili_data"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - wget
        - "--no-verbose"
        - "--spider"
        - "http://localhost:7700/health"
      retries: 3
      timeout: 5s
  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-pgsql:
    driver: local
  sail-pgsql_test:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
